build:
  maxIssues: 0
config:
  validation: true
  warningsAsErrors: true
potential-bugs:
  active: true

  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  InvalidRange:
    active: true
  UnreachableCode:
    active: true
  UselessPostfixExpression:
    active: true
  UnsafeCallOnNullableType:
    active: true
